use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
config :sunshine, SunshineWeb.Endpoint,
  handler: Phoenix.Endpoint.Cowboy2Handler,
  url: [scheme: "https", host: "example.com", port: 80],
  https: [
    port: 4001,
    certfile: "./priv/dev/server.pem",
    keyfile: "./priv/dev/server.key",
    versions: [:"tlsv1.2"],
    ciphers: [
      "ECDHE-ECDSA-AES256-GCM-SHA384",
      "ECDHE-RSA-AES256-GCM-SHA384",
      "ECDHE-ECDSA-AES256-SHA384",
      "ECDHE-RSA-AES256-SHA384",
      "ECDHE-ECDSA-DES-CBC3-SHA",
      "ECDH-ECDSA-AES256-GCM-SHA384",
      "ECDH-RSA-AES256-GCM-SHA384",
      "ECDH-ECDSA-AES256-SHA384",
      "ECDH-RSA-AES256-SHA384",
      "DHE-DSS-AES256-GCM-SHA384",
      "DHE-DSS-AES256-SHA256",
      "AES256-GCM-SHA384",
      "AES256-SHA256",
      "ECDHE-ECDSA-AES128-GCM-SHA256",
      "ECDHE-RSA-AES128-GCM-SHA256",
      "ECDHE-ECDSA-AES128-SHA256",
      "ECDHE-RSA-AES128-SHA256",
      "ECDH-ECDSA-AES128-GCM-SHA256",
      "ECDH-RSA-AES128-GCM-SHA256",
      "ECDH-ECDSA-AES128-SHA256",
      "ECDH-RSA-AES128-SHA256",
      "DHE-DSS-AES128-GCM-SHA256",
      "DHE-DSS-AES128-SHA256",
      "AES128-GCM-SHA256",
      "AES128-SHA256",
      "ECDHE-ECDSA-AES256-SHA",
      "ECDHE-RSA-AES256-SHA",
      "DHE-DSS-AES256-SHA",
      "ECDH-ECDSA-AES256-SHA",
      "ECDH-RSA-AES256-SHA",
      "AES256-SHA",
      "ECDHE-ECDSA-AES128-SHA",
      "ECDHE-RSA-AES128-SHA",
      "DHE-DSS-AES128-SHA",
      "ECDH-ECDSA-AES128-SHA",
      "ECDH-RSA-AES128-SHA",
      "AES128-SHA"
    ],
    secure_renegotiate: true,
    reuse_sessions: true,
    honor_cipher_order: true,
    max_connections: :infinity
  ],
  http: [
    port: 4002
  ],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin",
                    cd: Path.expand("../assets", __DIR__)]]
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :sunshine, SunshineWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/sunshine_web/views/.*(ex)$},
      ~r{lib/sunshine_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :sunshine, Sunshine.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "postgres",
  database: "sunshine_dev",
  hostname: "localhost",
  pool_size: 10
